#:schema node_modules/wrangler/config-schema.json
name = "web"
compatibility_date = "2024-11-12"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[r2_buckets]]
bucket_name = "czqm"
binding = "bucket"