#:schema node_modules/wrangler/config-schema.json
name = "web"
compatibility_date = "2024-11-12"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "czqm-test"
database_id = "060fbe95-2147-4733-bc50-7888624b48e9"
preview_database_id = "DB"